#!/usr/bin/env zsh
# Build the 29er Rust staticlib and wrap it as an xcframework at
# ios/29er/Vendor/NmpApp29er.xcframework.
#
# 29er links one aggregate Rust archive (`-lnmp_app_29er`) that contains
# nmp-core, nmp-native-runtime, and the 29er per-app UniFFI facade. UniFFI Swift
# bindings (Bridge/Generated/nmp_app_29erFFI.h + nmp_app_29er.swift) are
# pre-generated by `crates/nmp-app-29er`'s `uniffi-bindgen` binary — see
# `scripts/check-uniffi-bindings-drift.sh` — they are NOT produced by this
# script and do not need an iOS cross-compile to regenerate.
#
# Mirrors the upstream NMP justfile's `rust-ios-sim` / `rust-ios-device`
# recipes but produces an xcframework instead of loose archives in `target/`.
#
# Run from the repo root:
#   scripts/build-nmp-xcframework.sh            # debug, sim only (fast)
#   scripts/build-nmp-xcframework.sh --release   # release, sim + device
#   scripts/build-nmp-xcframework.sh --device    # add device slice
#
# Idempotent: re-running rebuilds the archives and recreates the xcframework.
#
# NOTE: `ios/29er/project.yml`'s LIBRARY_SEARCH_PATHS already falls back to
# the plain `target/aarch64-apple-ios*/{debug,release}` directories that a
# bare `cargo build --target ...` produces, so this xcframework is *not*
# required for local iOS development — it only matters for distributing a
# prebuilt slice to a consumer without a Rust toolchain. The xcframework is
# gitignored; nothing commits its output. The plain cargo dirs also carry a
# sibling `libnmp_app_29er.dylib` (cargo builds cdylib + staticlib in one
# invocation); a preBuildScript on the Xcode target strips that dylib before
# every build so the linker can't pick it up over the archive — see the
# "Force static Rust link" phase in project.yml. This xcframework is
# unaffected: `-create-xcframework -library` below only ever wraps the `.a`.

set -euo pipefail

REPO_ROOT="${0:A:h:h}"
PACKAGE="nmp-app-29er"
OUT_DIR="$REPO_ROOT/ios/29er/Vendor"
XCFRAMEWORK="$OUT_DIR/NmpApp29er.xcframework"
SIM_TARGET="aarch64-apple-ios-sim"
DEVICE_TARGET="aarch64-apple-ios"
PROFILE="debug"
BUILD_DEVICE=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --release)
            PROFILE="release"
            ;;
        --device)
            BUILD_DEVICE=1
            ;;
        *)
            echo "Unknown option: $1" >&2
            echo "Usage: $0 [--release] [--device]" >&2
            exit 2
            ;;
    esac
    shift
done

# Release builds for the device target require IPHONEOS_DEPLOYMENT_TARGET to
# avoid the ___chkstk_darwin linker error introduced by Xcode 26 (matches
# upstream NMP justfile `rust-ios-device`).
if [[ "$PROFILE" == "release" && "$BUILD_DEVICE" == "1" ]]; then
    export IPHONEOS_DEPLOYMENT_TARGET=17.0
fi

echo "==> Building $PACKAGE ($PROFILE) for $SIM_TARGET"
cd "$REPO_ROOT"
if [[ "$PROFILE" == "release" ]]; then
    cargo build --release -p "$PACKAGE" --target "$SIM_TARGET"
else
    cargo build -p "$PACKAGE" --target "$SIM_TARGET"
fi

SIM_LIB="$REPO_ROOT/target/$SIM_TARGET/$PROFILE/lib${PACKAGE//-/_}.a"
if [[ ! -f "$SIM_LIB" ]]; then
    echo "error: expected $SIM_LIB to exist after cargo build" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"
rm -rf "$XCFRAMEWORK"

# `xcodebuild -create-xcframework -library <archive>` (no `-headers`) keeps
# the archive's original filename inside each per-platform slice directory
# (e.g. `NmpApp29er.xcframework/ios-arm64-simulator/libnmp_app_29er.a`), which
# is exactly what `ios/29er/project.yml`'s `LIBRARY_SEARCH_PATHS` +
# `-lnmp_app_29er` expect. Headers aren't wrapped here: Swift consumes the
# UniFFI FFI declarations via `SWIFT_OBJC_BRIDGING_HEADER` pointing straight
# at the checked-in `Bridge/Generated/nmp_app_29erFFI.h`, not via an
# Xcode-framework header search, so there is nothing for this xcframework to
# carry beyond the archive itself.
if [[ "$BUILD_DEVICE" == "1" ]]; then
    echo "==> Building $PACKAGE ($PROFILE) for $DEVICE_TARGET"
    if [[ "$PROFILE" == "release" ]]; then
        cargo build --release -p "$PACKAGE" --target "$DEVICE_TARGET"
    else
        cargo build -p "$PACKAGE" --target "$DEVICE_TARGET"
    fi
    DEVICE_LIB="$REPO_ROOT/target/$DEVICE_TARGET/$PROFILE/lib${PACKAGE//-/_}.a"
    if [[ ! -f "$DEVICE_LIB" ]]; then
        echo "error: expected $DEVICE_LIB to exist after cargo build" >&2
        exit 1
    fi
    echo "==> Assembling $XCFRAMEWORK (sim + device)"
    xcodebuild -create-xcframework \
        -library "$SIM_LIB" \
        -library "$DEVICE_LIB" \
        -output "$XCFRAMEWORK"
else
    echo "==> Assembling $XCFRAMEWORK (sim only)"
    xcodebuild -create-xcframework \
        -library "$SIM_LIB" \
        -output "$XCFRAMEWORK"
fi

echo "==> Done: $XCFRAMEWORK"
